# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-12-29 14:53:07
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb", workspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb"):
        gis_osm_pois_bog = "gis_osm_pois_bog"

        # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
        gis_osm_pois_bog_7_, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=gis_osm_pois_bog, selection_type="NEW_SELECTION", where_clause="fclass = 'park' Or fclass = 'museum' Or fclass = 'artwork' Or fclass = 'art_centre'", invert_where_clause="")

        # Process: Kernel Density (Kernel Density) (sa)
        KernelD_CULT = "C:\\Users\\ga.castillo\\Documents\\ArcGIS\\Packages\\Clase 12 - RestultadoFinal_13de63\\p20\\clase_8_parte_2.gdb\\KernelD_CULT"
        Kernel_Density = KernelD_CULT
        with arcpy.EnvManager(extent="-8262531,28908408 475737,346723986 -8236143,32138604 539068,431910021", mask="BOG_CentroPoblado_Project", scratchWorkspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb", 
                              workspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb"):
            KernelD_CULT = arcpy.sa.KernelDensity(in_features=gis_osm_pois_bog_7_, population_field="NONE", cell_size="9,48188587999994E-04", search_radius=None, area_unit_scale_factor="SQUARE_MAP_UNITS", out_cell_values="DENSITIES", method="PLANAR", in_barriers="")
            KernelD_CULT.save(Kernel_Density)


        # Process: Select Layer By Attribute (2) (Select Layer By Attribute) (management)
        gis_osm_pois_bog_3_, Count_2_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=gis_osm_pois_bog, selection_type="NEW_SELECTION", where_clause="fclass = 'school' Or fclass = 'university' Or fclass = 'college'", invert_where_clause="")

        # Process: Kernel Density (2) (Kernel Density) (sa)
        KernelD_EDUC = "C:\\Users\\ga.castillo\\Documents\\ArcGIS\\Packages\\Clase 12 - RestultadoFinal_13de63\\p20\\clase_8_parte_2.gdb\\KernelD_EDUC"
        Kernel_Density_2_ = KernelD_EDUC
        with arcpy.EnvManager(extent="-8262531,28908408 475737,346723986 -8236143,32138604 539068,431910021", mask="BOG_CentroPoblado_Project", scratchWorkspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb", 
                              workspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb"):
            KernelD_EDUC = arcpy.sa.KernelDensity(in_features=gis_osm_pois_bog_3_, population_field="NONE", cell_size="9,48188587999994E-04", search_radius=None, area_unit_scale_factor="SQUARE_MAP_UNITS", out_cell_values="DENSITIES", method="PLANAR", in_barriers="")
            KernelD_EDUC.save(Kernel_Density_2_)


        # Process: Select Layer By Attribute (3) (Select Layer By Attribute) (management)
        gis_osm_pois_bog_4_, Count_3_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=gis_osm_pois_bog, selection_type="NEW_SELECTION", where_clause="fclass = 'supermarket' Or fclass = 'convenience' Or fclass = 'fast_food' Or fclass = 'greengrocer' Or fclass = 'restaurant'", invert_where_clause="")

        # Process: Kernel Density (3) (Kernel Density) (sa)
        KernelD_ALIM = "C:\\Users\\ga.castillo\\Documents\\ArcGIS\\Packages\\Clase 12 - RestultadoFinal_13de63\\p20\\clase_8_parte_2.gdb\\KernelD_ALIM"
        Kernel_Density_3_ = KernelD_ALIM
        with arcpy.EnvManager(extent="-8262531,28908408 475737,346723986 -8236143,32138604 539068,431910021", mask="BOG_CentroPoblado_Project", scratchWorkspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb", 
                              workspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb"):
            KernelD_ALIM = arcpy.sa.KernelDensity(in_features=gis_osm_pois_bog_4_, population_field="NONE", cell_size="9,48188587999994E-04", search_radius=None, area_unit_scale_factor="SQUARE_MAP_UNITS", out_cell_values="DENSITIES", method="PLANAR", in_barriers="")
            KernelD_ALIM.save(Kernel_Density_3_)


        # Process: Select Layer By Attribute (4) (Select Layer By Attribute) (management)
        gis_osm_pois_bog_5_, Count_4_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=gis_osm_pois_bog, selection_type="NEW_SELECTION", where_clause="fclass = 'bank' Or fclass = 'optician' Or fclass = 'doctors' Or fclass = 'atm' Or fclass = 'beauty_shop'", invert_where_clause="")

        # Process: Kernel Density (4) (Kernel Density) (sa)
        KernelD_SERV = "C:\\Users\\ga.castillo\\Documents\\ArcGIS\\Packages\\Clase 12 - RestultadoFinal_13de63\\p20\\clase_8_parte_2.gdb\\KernelD_SERV"
        Kernel_Density_4_ = KernelD_SERV
        with arcpy.EnvManager(extent="-8262531,28908408 475737,346723986 -8236143,32138604 539068,431910021", mask="BOG_CentroPoblado_Project", scratchWorkspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb", 
                              workspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb"):
            KernelD_SERV = arcpy.sa.KernelDensity(in_features=gis_osm_pois_bog_5_, population_field="NONE", cell_size="9,48188587999994E-04", search_radius=None, area_unit_scale_factor="SQUARE_MAP_UNITS", out_cell_values="DENSITIES", method="PLANAR", in_barriers="")
            KernelD_SERV.save(Kernel_Density_4_)


        # Process: Select Layer By Attribute (5) (Select Layer By Attribute) (management)
        gis_osm_pois_bog_6_, Count_5_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=gis_osm_pois_bog, selection_type="NEW_SELECTION", where_clause="fclass = 'bar' Or fclass = 'mall' Or fclass = 'theatre' Or fclass = 'cinema'", invert_where_clause="")

        # Process: Kernel Density (5) (Kernel Density) (sa)
        KernelD_OCIO = "C:\\Users\\ga.castillo\\Documents\\ArcGIS\\Packages\\Clase 12 - RestultadoFinal_13de63\\p20\\clase_8_parte_2.gdb\\KernelD_OCIO"
        Kernel_Density_5_ = KernelD_OCIO
        with arcpy.EnvManager(extent="-8262531,28908408 475737,346723986 -8236143,32138604 539068,431910021", mask="BOG_CentroPoblado_Project", scratchWorkspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb", 
                              workspace=r"C:\Users\ga.castillo\Documents\ArcGIS\Packages\Clase 12 - RestultadoFinal_13de63\p20\clase_8_parte_2.gdb"):
            KernelD_OCIO = arcpy.sa.KernelDensity(in_features=gis_osm_pois_bog_6_, population_field="NONE", cell_size="9,48188587999994E-04", search_radius=None, area_unit_scale_factor="SQUARE_MAP_UNITS", out_cell_values="DENSITIES", method="PLANAR", in_barriers="")
            KernelD_OCIO.save(Kernel_Density_5_)


if __name__ == '__main__':
    Model()
